# Generated by Django 3.1.4 on 2021-07-23 18:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кафедры')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='Аббревиатура')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(help_text='Максимальная длина 50 символов', max_length=50, verbose_name='Фамилия преподавателя')),
                ('first_name', models.CharField(help_text='Максимальная длина 50 символов', max_length=50, verbose_name='Имя преподавателя')),
                ('middle_name', models.CharField(help_text='Максимальная длина 50 символов', max_length=50, verbose_name='Отчество преподавателя')),
                ('position', models.CharField(choices=[('Старший преподаватель', 'Senior Lecturer'), ('Преподаватель', 'Junior Lecturer'), ('Доцент', 'Docent'), ('PhD', 'Phd')], default='Старший преподаватель', max_length=30, verbose_name='Должность')),
                ('phone_number', models.CharField(blank=True, help_text='Пример: +7-708-999-99-99. Пробелы и тире можно не писать', max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='\\+7[ -]?7[0-9]{2}[ -]?[0-9]{3}[ -]?[0-9]{2}[ -]?[0-9]{2}')], verbose_name='Номер телефона преподавателя')),
                ('slug', models.SlugField(blank=True, help_text='Устанавливается автоматически ', max_length=200, null=True, unique=True, verbose_name='Удобное представления URL')),
                ('kstu_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на преподавателя на сайте KSTU')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail преподавателя')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['second_name', 'first_name'],
                'unique_together': {('first_name', 'second_name', 'middle_name')},
            },
        ),
    ]
