# Generated by Django 3.1.4 on 2021-07-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210724_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='slug',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(choices=[('Старший преподаватель', 'Senior Lecturer'), ('Преподаватель', 'Junior Lecturer'), ('Доцент', 'Docent'), ('PhD', 'Phd')], default='Старший преподаватель', max_length=30, verbose_name='Должность'),
        ),
    ]
