# Generated by Django 3.1.4 on 2021-01-05 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20201228_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail преподавателя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Пример: +7-708-999-99-99. Пробелы и тире можно не писать', max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='\\+7[ -]?7[0-9]{2}[ -]?[0-9]{3}[ -]?[0-9]{2}[ -]?[0-9]{2}')], verbose_name='Номер телефона преподавателя'),
        ),
    ]
