# Generated by Django 3.1.4 on 2021-07-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20210105_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(choices=[('Старший преподаватель', 'Senior Lecturer'), ('Преподаватель', 'Junior Lecturer'), ('Доцент', 'Docent'), ('PhD', 'Phd')], default='Старший преподаватель', max_length=30, verbose_name='Должность'),
        ),
        migrations.DeleteModel(
            name='TeacherPosition',
        ),
    ]
