# Generated by Django 3.1.4 on 2021-07-23 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Лекция', 'Lecture'), ('Лабораторное занятие', 'Lab'), ('Семинар', 'Seminar'), ('СРСП', 'Srsp'), ('СРС', 'Srs'), ('Кураторский час', 'Curatorial Hour')], default='Лекция', max_length=50, verbose_name='Тип занятия')),
                ('time', models.TimeField(verbose_name='Время начала занятия')),
                ('day', models.CharField(choices=[('Понедельник', 'Monday'), ('Вторник', 'Tuesday'), ('Среда', 'Wednesday'), ('Четверг', 'Thursday'), ('Пятница', 'Friday'), ('Суббота', 'Saturday'), ('Воскресенье', 'Sunday')], default='Понедельник', max_length=20, verbose_name='День недели')),
                ('parity', models.CharField(choices=[('Числитель', 'Numerator'), ('Знаменатель', 'Denominator'), ('Всегда', 'Always')], default='Числитель', max_length=15, verbose_name='Четность недели')),
                ('archived', models.BooleanField(default=False, verbose_name='Заархивированный предмет')),
                ('next_assignment', models.TextField(blank=True, null=True, verbose_name='Следующая домашка')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Название предмета')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
                'ordering': ['day'],
                'unique_together': {('subject', 'parity', 'day', 'time'), ('subject', 'parity', 'day', 'teacher', 'time')},
            },
        ),
    ]
