# Generated by Django 3.1.3 on 2020-11-19 05:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20201113_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='my_playlist_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Сыылка на плейлист на моем канале'),
        ),
        migrations.AddField(
            model_name='subject',
            name='official_playlist_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на плейлист на канале КарТУ'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Пример: +7708-999-99-99', max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='\\+77[0-9]{2}-[0-9]{3}-[0-9]{2}-[0-9]{2}')], verbose_name='Номер телефона преподавателя'),
        ),
        migrations.AlterField(
            model_name='dayofweek',
            name='is_numerator',
            field=models.BooleanField(verbose_name='Является ли числителем'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='kind',
            field=models.CharField(choices=[('LE', 'Лекция'), ('LA', 'Лабораторная работа'), ('PR', 'Практика'), ('SP', 'СРСП'), ('SS', 'СРС'), ('CH', 'Кураторский час')], default='LE', max_length=2, verbose_name='Тип занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.TimeField(verbose_name='Время начала занятия'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lab_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_teacher', to='schedule.teacher', verbose_name='Имя преподавателя, ведущего лабораторные'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer', to='schedule.teacher', verbose_name='Имя лектора'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='practic_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practic_teacher', to='schedule.teacher', verbose_name='Имя преподавателя, ведущего практику'),
        ),
    ]
