# Generated by Django 3.1.4 on 2020-12-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20201218_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['name'], 'verbose_name': 'День недели', 'verbose_name_plural': 'Дни недели'},
        ),
        migrations.AlterModelOptions(
            name='lessonkind',
            options={'ordering': ['name'], 'verbose_name': 'Тип пары', 'verbose_name_plural': 'Типы пары'},
        ),
        migrations.AddField(
            model_name='day',
            name='code',
            field=models.CharField(max_length=10, null=True, verbose_name='Сокращенное название'),
        ),
    ]
