# Generated by Django 3.1.3 on 2020-11-20 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20201119_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(blank=True, help_text='Устанавливается автоматически ', max_length=200, null=True, unique=True, verbose_name='Удобное представления URL'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Пример: +7708-999-99-99', max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='\\+77[0-9]{2}[ -]?[0-9]{3}[ -]?[0-9]{2}[ -]?[0-9]{2}')], verbose_name='Номер телефона преподавателя'),
        ),
    ]
