# Generated by Django 3.1.4 on 2020-12-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20201219_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='index',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.day', verbose_name='_День недели'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_numerator',
            field=models.BooleanField(null=True, verbose_name='Числитель/знаменатель'),
        ),
        migrations.DeleteModel(
            name='DaySchedule',
        ),
    ]
