# Generated by Django 3.1.3 on 2020-12-12 15:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20201120_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, help_text='Устанавливается автоматически ', max_length=200, null=True, unique=True, verbose_name='Удобное представления URL'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lab_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_set', to='schedule.teacher', verbose_name='Имя преподавателя, ведущего лабораторные'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture_set', to='schedule.teacher', verbose_name='Имя лектора'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='my_playlist_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на плейлист на моем канале'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Не более 50 символов', max_length=50, verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='practic_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practic_set', to='schedule.teacher', verbose_name='Имя преподавателя, ведущего практику'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Пример: +7708-999-99-99', max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='\\+7[ -]?7[0-9]{2}[ -]?[0-9]{3}[ -]?[0-9]{2}[ -]?[0-9]{2}')], verbose_name='Номер телефона преподавателя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(choices=[('SL', 'Старший преподаватель'), ('JL', 'Преподаватель'), ('DO', 'Доцент'), ('CS', 'Кандидат технических наук'), ('DS', 'Доктор Технических наук')], default='JL', max_length=2, verbose_name='Должность'),
        ),
    ]
