# Generated by Django 3.1.4 on 2020-12-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20201228_2153'),
        ('schedule', '0006_auto_20201228_2153'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('subject', 'is_numerator', 'day', 'teacher', 'time')},
        ),
    ]
