# Generated by Django 3.1.4 on 2021-01-03 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20201228_2153'),
        ('schedule', '0011_auto_20210103_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.day', verbose_name='День недели'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('subject', 'parity', 'day', 'teacher', 'time')},
        ),
    ]
