# Generated by Django 3.1.4 on 2021-01-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20210103_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_numerator',
        ),
    ]
