# Generated by Django 3.1.4 on 2021-01-06 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20210105_2042'),
        ('schedule', '0014_remove_lesson_is_numerator'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='next_assignment',
            field=models.TextField(blank=True, null=True, verbose_name='Следующая домашка'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lab_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_set', to='teachers.teacher', verbose_name='Преподаватель, ведущий лабораторные'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture_set', to='teachers.teacher', verbose_name='Лектора'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='practic_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practic_set', to='teachers.teacher', verbose_name='Преподаватель, ведущий практику'),
        ),
    ]
