# Generated by Django 3.1.4 on 2021-07-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_subject_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='kind',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='kind',
            field=models.CharField(choices=[('LEC', 'Лекция'), ('LAB', 'Лабораторное занятие'), ('PRC', 'Семинар'), ('SRSP', 'СРСП'), ('SRS', 'СРС'), ('CUR', 'Кураторский час')], default='LEC', max_length=50, verbose_name='Тип занятия'),
        ),
        migrations.DeleteModel(
            name='LessonKind',
        ),
    ]
