# Generated by Django 3.1.4 on 2021-07-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_auto_20210723_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
