# Generated by Django 3.1.4 on 2021-07-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_delete_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.CharField(choices=[('Понедельник', 'понедельник'), ('Вторник', 'вторник'), ('Среда', 'среда'), ('Четверг', 'четверг'), ('Пятница', 'пятница'), ('Суббота', 'суббота'), ('Воскресенье', 'воскресенье')], default='mon', max_length=20, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='kind',
            field=models.CharField(choices=[('Лекция', 'лекция'), ('Лабораторное занятие', 'лабораторное занятие'), ('Семинар', 'семинар'), ('СРСП', 'СРСП'), ('СРС', 'СРС'), ('Кураторский час', 'кураторский час')], default='LEC', max_length=50, verbose_name='Тип занятия'),
        ),
    ]
