# Generated by Django 3.1.4 on 2021-07-23 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('schedule', '0026_auto_20210723_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Название предмета'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
