# Generated by Django 3.1.4 on 2021-07-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_auto_20210723_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.CharField(choices=[('Понедельник', 'Monday'), ('Вторник', 'Tuesday'), ('Среда', 'Wednesday'), ('Четверг', 'Thursday'), ('Пятница', 'Friday'), ('Суббота', 'Saturday'), ('Воскресенье', 'Sunday')], default='Понедельник', max_length=20, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='kind',
            field=models.CharField(choices=[('Лекция', 'Lecture'), ('Лабораторное занятие', 'Lab'), ('Семинар', 'Seminar'), ('СРСП', 'Srsp'), ('СРС', 'Srs'), ('Кураторский час', 'Curatorial Hour')], default='Лекция', max_length=50, verbose_name='Тип занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='parity',
            field=models.CharField(choices=[('Числитель', 'Numerator'), ('Знаменатель', 'Denominator'), ('Всегда', 'Always')], default='Числитель', max_length=15, verbose_name='Четность недели'),
        ),
    ]
