# Generated by Django 3.1.4 on 2021-07-24 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('teachers', '0003_auto_20210724_1125'),
        ('subjects', '0002_auto_20210724_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectname',
            options={'ordering': ['name'], 'verbose_name': 'Название предмета', 'verbose_name_plural': 'Названия предметов'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='slug',
        ),
        migrations.AlterField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='Группа, у которой ведется предмет'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture_set', to='teachers.teacher', verbose_name='Лектор'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subjectname', verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subgroup',
            field=models.IntegerField(choices=[(1, 'First Group'), (2, 'Second Group'), (3, 'Both')], default=3, verbose_name='Подгруппа, у которой ведется предмет'),
        ),
    ]
