# Generated by Django 3.1.4 on 2021-07-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20210724_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subgroup',
            field=models.IntegerField(choices=[(1, 'First Group'), (2, 'Second Group'), (3, 'Both')], default=3, verbose_name='Подгруппа, у которой ведется предмет'),
        ),
    ]
